all:
  vars: 
    ansible_ssh_private_key_file: test.pem
    ansible_user: ec2-user 
  hosts: # all ungrouped hosts

  children: # group of hosts
    webservers: # first group of hosts
      hosts:
        web1:
          ansible_host: 172.31.16.132
         # ansible_user: ec2-user 
         # ansible_ssh_private_key_file: test.pem
        web2:
          ansible_host: 172.31.16.216
         # ansible_user: ec2-user
    databases: # second group of hosts
      hosts: 
        db_server:
          ansible_host: 172.31.17.11
          ansible_user: ec2-user 

